"""initial_schema

Revision ID: 678454604126
Revises: 
Create Date: 2026-09-20 16:15:05.557525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '678454604126'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('caregivers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('relationship_to_patient', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('anonymous_alias', sa.String(length=100), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('font_scale_preference', sa.Float(), nullable=False),
    sa.Column('contrast_preference', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('local_id', sa.String(length=36), nullable=False),
    sa.Column('game_type', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('mistakes', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('hint_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'local_id', name='uq_patient_game_session_local_id')
    )
    op.create_index(op.f('ix_game_sessions_local_id'), 'game_sessions', ['local_id'], unique=False)
    op.create_index(op.f('ix_game_sessions_patient_id'), 'game_sessions', ['patient_id'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('local_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('relationship', sa.String(length=100), nullable=True),
    sa.Column('person_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('audio_path', sa.String(length=500), nullable=True),
    sa.Column('media_uri', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'local_id', name='uq_patient_memory_local_id')
    )
    op.create_index(op.f('ix_memories_local_id'), 'memories', ['local_id'], unique=False)
    op.create_index(op.f('ix_memories_patient_id'), 'memories', ['patient_id'], unique=False)
    op.create_table('patient_caregivers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('caregiver_id', sa.String(length=36), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['caregivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'caregiver_id', name='uq_patient_caregiver')
    )
    op.create_index(op.f('ix_patient_caregivers_caregiver_id'), 'patient_caregivers', ['caregiver_id'], unique=False)
    op.create_index(op.f('ix_patient_caregivers_patient_id'), 'patient_caregivers', ['patient_id'], unique=False)
    op.create_table('reminder_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('local_id', sa.String(length=36), nullable=False),
    sa.Column('reminder_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'local_id', name='uq_patient_reminder_event_local_id')
    )
    op.create_index(op.f('ix_reminder_events_local_id'), 'reminder_events', ['local_id'], unique=False)
    op.create_index(op.f('ix_reminder_events_patient_id'), 'reminder_events', ['patient_id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('local_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=False),
    sa.Column('scheduled_time', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'local_id', name='uq_patient_reminder_local_id')
    )
    op.create_index(op.f('ix_reminders_local_id'), 'reminders', ['local_id'], unique=False)
    op.create_index(op.f('ix_reminders_patient_id'), 'reminders', ['patient_id'], unique=False)
    op.create_table('routines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('local_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('steps_json', sa.Text(), nullable=False),
    sa.Column('preferred_time', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'local_id', name='uq_patient_routine_local_id')
    )
    op.create_index(op.f('ix_routines_local_id'), 'routines', ['local_id'], unique=False)
    op.create_index(op.f('ix_routines_patient_id'), 'routines', ['patient_id'], unique=False)
    op.create_table('sync_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('operation_id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('local_id', sa.String(length=36), nullable=False),
    sa.Column('server_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('client_updated_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_operations_local_id'), 'sync_operations', ['local_id'], unique=False)
    op.create_index(op.f('ix_sync_operations_operation_id'), 'sync_operations', ['operation_id'], unique=True)
    op.create_index(op.f('ix_sync_operations_patient_id'), 'sync_operations', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_operations_patient_id'), table_name='sync_operations')
    op.drop_index(op.f('ix_sync_operations_operation_id'), table_name='sync_operations')
    op.drop_index(op.f('ix_sync_operations_local_id'), table_name='sync_operations')
    op.drop_table('sync_operations')
    op.drop_index(op.f('ix_routines_patient_id'), table_name='routines')
    op.drop_index(op.f('ix_routines_local_id'), table_name='routines')
    op.drop_table('routines')
    op.drop_index(op.f('ix_reminders_patient_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_local_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_reminder_events_patient_id'), table_name='reminder_events')
    op.drop_index(op.f('ix_reminder_events_local_id'), table_name='reminder_events')
    op.drop_table('reminder_events')
    op.drop_index(op.f('ix_patient_caregivers_patient_id'), table_name='patient_caregivers')
    op.drop_index(op.f('ix_patient_caregivers_caregiver_id'), table_name='patient_caregivers')
    op.drop_table('patient_caregivers')
    op.drop_index(op.f('ix_memories_patient_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_local_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_game_sessions_patient_id'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_local_id'), table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_table('patients')
    op.drop_table('caregivers')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
