"""SyncOperation model for enforcing operation-level idempotency and audit tracking.

Every SyncQueue item generated by the client carries a distinct operation_id.
Retries of the same queue item retain the same operation_id, ensuring
the backend can recognize already-processed operations without duplicating data.
"""
import uuid
from datetime import datetime, timezone
from sqlalchemy import Column, String, DateTime, ForeignKey
from backend.api.app.db.base import Base

class SyncOperation(Base):
    __tablename__ = "sync_operations"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    operation_id = Column(String(64), unique=True, index=True, nullable=False)
    patient_id = Column(String(36), ForeignKey("patients.id", ondelete="CASCADE"), nullable=False, index=True)
    entity_type = Column(String(50), nullable=False)  # Memories, GameSessions, Reminders, ReminderEvents, Routines
    operation = Column(String(20), nullable=False)    # CREATE, UPDATE, DELETE
    local_id = Column(String(36), nullable=False, index=True)  # The entity's localId
    server_id = Column(String(36), nullable=True)     # The entity's server-assigned ID
    status = Column(String(30), nullable=False, default="synced")  # synced, already_processed, conflict, rejected
    client_updated_at = Column(DateTime, nullable=True)
    processed_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)
